#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Motors
  Team Members: Caleb Looney, Emma O'Neal
  Date: 12/16
  Section: N/A


  Task Description:
  Run the right motor at half speed for 5 seconds
  Then run the right motor in reverse at half speed for 5 seconds


  Pseudocode:
  Start right motor at half speed (63)
  Wait 5 seconds
  Stop right motor
  Wait 2 seconds
  start right motor at half speed in reverse (-63)
  wait 5 seconds
  stop right motor
  wait 2 seconds

*/

task main()
{                                     //Program begins, insert code within curly braces
	startMotor(rightMotor, 63);	// Start right motor at half speed
	startMotor(leftMotor, 63); // start left motor at half speed
  wait(5);	// Wait 5 seconds
  stopMotor(rightMotor); //Stop right motor
  stopMotor(leftMotor); // stop left motor
  wait(2);	// Wait 2 seconds
  startMotor(rightMotor, -63); // start right motor at half speed in reverse
  startMotor(leftMotor, -63); // start left motor in reverse
  wait(5); // wait 5 seconds
  stopMotor(rightMotor); //stop right motor
  stopMotor(leftMotor); // stop left motor
  wait(2); //wait 2 seconds

  // turn on leftmotor at same times

}
