#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members:
  Date:
  Section:


  Task Description:


  Pseudocode:
	//turn tight motor on forward at half speed for 5 seconds and stop
// turn the left motor on in reverse at 3/4 speed for 2.5 seconds
// turn both motors on at foll power silw sinning in the same direction for 7.25 seconds and then stop.
*/

task main()
{                                     //Program begins, insert code within curly braces
	startMotor(rightMotor, 63);
	wait(5);
	stopMotor(rightMotor);
	startMotor(leftMotor, 94);
	wait(2.5);
	stopMotor(leftMotor);
	startMotor(rightMotor, 127);
	startMotor(leftMotor, 127);
	wait(7.25);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
}
