#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members:
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
setServo(servoMotor, -127); //set servo -127
wait(2); //wait 2 second
setServo(servoMotor, -63); //set servo at -63
wait(3); //wait 3 seconds
setServo(servoMotor, 63); //set servo 63
wait(3); //wait 3 seconds
setServo(servoMotor, 127); //set servo 127
wait(2); //wait 2 seconds



}
