#pragma config(Sensor, dgtl1,  elbowActuator,  sensorTouch)
#pragma config(Sensor, dgtl2,  wristActuator,  sensorTouch)
#pragma config(Sensor, dgtl3,  tableActuator,  sensorTouch)
#pragma config(Sensor, dgtl4,  gripperActuator, sensorTouch)
#pragma config(Sensor, dgtl5,  leftButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  rightButton,    sensorTouch)
#pragma config(Sensor, dgtl7,  eStop,          sensorTouch)
#pragma config(Motor,  port2,           elbowMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           tableMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           gripperMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           wristMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(eStop) != 1){     //forever loop that allows everything inside it to run
		//section of code below runs the wrist, once the wrist activator button is
		//continuously pressed, it allows you to press either the left or right
		// button which allows you to rotate the wrist left or right.
		if(sensorValue(wristActuator) == 1){
			if(sensorValue(leftButton) == 1) {
				startMotor(wristMotor, 40);
			}
			else if((SensorValue(rightButton) == 1)){
				startMotor(wristMotor, -40);
			} else {
				stopMotor(wristMotor);
			}
		} else {
			stopMotor(wristMotor);
		}
		//section of code below runs the elbow, once the elbow activator button is
		//pressed, it allows you to press either the left or right button which
		//allows you to either extend the elbow or close the elbow
		if(sensorValue(elbowActuator) == 1){
			if(SensorValue(rightButton) == 1){
				startMotor(elbowMotor, 40);
			} else if(SensorValue(leftButton) == 1){
				startMotor(elbowMotor, -40);
			} else {
			stopMotor(elbowMotor);
		}
		}
		//section of code below runs table motor (motor spins arm), once the table
		//activator button is pressed, it allows you to press either the left or
		//right button which allows you to either rotate the whole arm left or right
		if(sensorValue(tableActuator) == 1){
			if(sensorValue(rightButton) == 1){
				startMotor(tableMotor, 40);
			} else if(sensorValue(leftButton) == 1){
				startMotor(tableMotor, -40);
			} else {
				stopMotor(tableMotor);
			}
		}
		//section of code below runs the claw, once the gripper activator button is
		//pressed, it allows you to press either the left or right button which
		//allows you to either open or close the grapper
		if(sensorValue(gripperActuator) == 1){
			if(sensorValue(rightButton) == 1){
				startMotor(gripperMotor, 40);
			} else if (sensorValue(leftButton) == 1){
				startMotor(gripperMotor, -40);
			} else {
				stopMotor(gripperMotor);
			}
		}
}

}
